# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cluster_service_pb2 as cluster__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cluster_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClusterCoordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/cluster.ClusterCoordinator/RequestVote',
                request_serializer=cluster__service__pb2.VoteRequest.SerializeToString,
                response_deserializer=cluster__service__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.BroadcastTopology = channel.unary_unary(
                '/cluster.ClusterCoordinator/BroadcastTopology',
                request_serializer=cluster__service__pb2.TopologyConfig.SerializeToString,
                response_deserializer=cluster__service__pb2.Ack.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/cluster.ClusterCoordinator/Ping',
                request_serializer=cluster__service__pb2.PingRequest.SerializeToString,
                response_deserializer=cluster__service__pb2.Ack.FromString,
                _registered_method=True)


class ClusterCoordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestVote(self, request, context):
        """Raft leader election: candidate requests a vote from a peer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastTopology(self, request, context):
        """Elected coordinator broadcasts final role assignments to all peers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Synchronization barrier to verify all hosts are online before election
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=cluster__service__pb2.VoteRequest.FromString,
                    response_serializer=cluster__service__pb2.VoteResponse.SerializeToString,
            ),
            'BroadcastTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastTopology,
                    request_deserializer=cluster__service__pb2.TopologyConfig.FromString,
                    response_serializer=cluster__service__pb2.Ack.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=cluster__service__pb2.PingRequest.FromString,
                    response_serializer=cluster__service__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cluster.ClusterCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cluster.ClusterCoordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterCoordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.ClusterCoordinator/RequestVote',
            cluster__service__pb2.VoteRequest.SerializeToString,
            cluster__service__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.ClusterCoordinator/BroadcastTopology',
            cluster__service__pb2.TopologyConfig.SerializeToString,
            cluster__service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.ClusterCoordinator/Ping',
            cluster__service__pb2.PingRequest.SerializeToString,
            cluster__service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
