# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tensor_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tensor_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14tensor_service.proto\x12\x0f\x62uddies_network\"S\n\x0bSplitConfig\x12\x17\n\x0fstart_layer_idx\x18\x01 \x01(\x05\x12\x15\n\rend_layer_idx\x18\x02 \x01(\x05\x12\x14\n\x0cis_tail_node\x18\x03 \x01(\x08\"\x1d\n\tConfigAck\x12\x10\n\x08is_ready\x18\x01 \x01(\x08\"p\n\x0e\x46orwardPayload\x12\x18\n\x10\x61\x63tivation_shape\x18\x01 \x03(\x03\x12\x18\n\x10\x61\x63tivation_bytes\x18\x02 \x01(\x0c\x12\x14\n\x0ctarget_shape\x18\x03 \x03(\x03\x12\x14\n\x0ctarget_bytes\x18\x04 \x01(\x0c\"U\n\x0f\x42\x61\x63kwardPayload\x12\x16\n\x0egradient_shape\x18\x01 \x03(\x03\x12\x16\n\x0egradient_bytes\x18\x02 \x01(\x0c\x12\x12\n\nloss_value\x18\x03 \x01(\x02\x32\xbc\x01\n\x0ePipelineRouter\x12O\n\x13\x41ssignConfiguration\x12\x1c.buddies_network.SplitConfig\x1a\x1a.buddies_network.ConfigAck\x12Y\n\x14\x45xecutePipelineStage\x12\x1f.buddies_network.ForwardPayload\x1a .buddies_network.BackwardPayloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tensor_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPLITCONFIG']._serialized_start=41
  _globals['_SPLITCONFIG']._serialized_end=124
  _globals['_CONFIGACK']._serialized_start=126
  _globals['_CONFIGACK']._serialized_end=155
  _globals['_FORWARDPAYLOAD']._serialized_start=157
  _globals['_FORWARDPAYLOAD']._serialized_end=269
  _globals['_BACKWARDPAYLOAD']._serialized_start=271
  _globals['_BACKWARDPAYLOAD']._serialized_end=356
  _globals['_PIPELINEROUTER']._serialized_start=359
  _globals['_PIPELINEROUTER']._serialized_end=547
# @@protoc_insertion_point(module_scope)
